baseURL = "https://taiwangoldcard.com/"
disableKinds = ["taxonomy", "taxonomyTerm"]
enableGitInfo = true
enableRobotsTXT = true
publishDir = "docs"
theme = "compose"
title = "Taiwan Gold Card - Taiwan Foreign Talent Community"
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
noClasses = false
style = "monokai"
tabWidth = 2
[[menu.main]]
name = "Life in Taiwan"
url = "goldcard-holders-faq/"
weight = 2
[[menu.main]]
name = "Application Process"
url = "application-faq/"
weight = 1
[params]
author = "Taiwan Gold Card Community"
description = "We are a strong community of professionals with Taiwan Gold Card visa. We happily help newcomers and support each other within the Gold Card community"
enableSearch = true
repo = "https://github.com/onweru/compose"
searchPlaceholder = "Search..."
time_format_blog = "Monday, January 02, 2006"
time_format_default = "January 2, 2006"
title = "Taiwan Gold Card | Taiwan Foreign Talent Community"
[params.logo]
darkMode = "gc-light.svg"
lightMode = "gc.svg"
[params.source]
icon = "github.svg"
name = "Apply"
url = "https://coa.immigration.gov.tw/coa-frontend/four-in-one/entry/golden-card"
