baseURL = "https://taiwangoldcard.com/"
title = "Taiwan Gold Card"
enableRobotsTXT = true
theme = "compose"
enableGitInfo = false
publishDir = "docs"

disableKinds = ["taxonomy", "taxonomyTerm"]

#  menu items
[[menu.main]]
    name = "Application Process"
    weight = 1
    url = "application-faq/"

[[menu.main]]
    name = "Life in Taiwan"
    weight = 2
    url = "goldcard-holders-faq/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 2

# Everything below this are Site Params

[params]
  author = "Taiwan Gold Card"
  enableSearch = false
  searchPlaceholder = "Search ..."
  repo = "https://github.com/onweru/compose"

  description = "Taiwan Gold Card Network"
  title = "Taiwan Gold Card"  

  time_format_blog = "Monday, January 02, 2006"
  time_format_default = "January 2, 2006"
  [params.logo]
    lightMode = "gc.svg"
    darkMode = "gc-light.svg"

  [params.source]
    name = "Apply"
    icon = "github.svg"
    url = "https://coa.immigration.gov.tw/coa-frontend/four-in-one/entry/golden-card"
