name: Tests

on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          start: hugo server
          wait-on: http://localhost:1313
